### ISSUE TITLE
Redesign main menu

### ISSUE THREAD

**Issue by dmkulazhenko** [Leemurus/Messenger#13]
Seems like current version of menu, which realized with "3 points" is inconvenient to use...
![image](https://user-images.githubusercontent.com/13505031/68924527-1bb9c300-0792-11ea-8d39-94c215e0d37a.png)

**Comment by dmkulazhenko** [comment]
StoryPoints: 8

**Comment by leemurus** [comment]
Was changed in https://github.com/Leemurus/Messenger/commit/983feadc1f8549c4fd696357e0fc82de6ddb0ef1
![image](https://user-images.githubusercontent.com/30449027/69275256-1f63a480-0bed-11ea-914c-5bb764655bfb.png)
