### ISSUE TITLE
Rewrite validation logic

### ISSUE THREAD

**Issue by leemurus** [Leemurus/Messenger#23]
New logic of classes for validation, which will exclude validation from routes.

**Comment by leemurus** [comment]
Added in https://github.com/Leemurus/Messenger/commit/e449a02407cf07905670ea1d82901689d1604a91

**Comment by dmkulazhenko** [comment]
Close issue, if u fixed it in e449a02407cf07905670ea1d82901689d1604a91.
If not -- do this task, bcs if u will add new features u will use old style of validation or 2 styles of validation.
